spring.application.name=CasosDeUso



#Cambien  los parametros del host, nombre y constraseña de la BD
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cambiar este valor
spring.datasource.username=cambiar este valor
spring.datasource.password=cambiar este valor
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: Recrea las tablas al iniciar y las borra al cerrar (ideal para pruebas)
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cargar el archivo data.sql o import.sql después de crear las tablas
spring.jpa.defer-datasource-initialization=true