spring.application.name=CasosDeUso
spring.config.import=optional:file:.env[.properties]



#Cambien  los parametros del host, nombre y constraseña de la BD
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:casosdeuso}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: Recrea las tablas al iniciar y las borra al cerrar (ideal para pruebas)
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cargar el archivo data.sql o import.sql después de crear las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
